name: Issues
on: 
    issues:
        types: [opened, edited]

jobs:
    output-issue:
        runs-on: ubuntu-latest
        steps:
            - name: Print Issues
              env: 
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"